{{- if and (not .Values.existingSecret.name) .Values.secrets.originVerify }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cf-image-optimize-proxy.fullname" . }}
  labels:
    {{- include "cf-image-optimize-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  CF_ORIGIN_SECRET: {{ join "," .Values.secrets.originVerify | quote }}
{{- end }}

